version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      # Android the primary container
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
 
  - run:
          name: Launch emulator
         - emulator -avd circleci-android22 -no-audio -no-window:
            background: true
            parallel: true
  - run:
          name: Wait emulator
          command: |
            # wait for it to have booted
            circle-android wait-for-boot
            # unlock the emulator screen
            sleep 30
            adb shell input keyevent 82
      
  - run:
          name: Run TestNG Tests
          command: java -cp "lib/*:bin/" org.testng.TestNG testng.xml
          
  - store_artifacts:
          path:  test-output
